name: Software_check
on:
  push:
  pull_request:
    types: [opened]
jobs:
  check_compile-job:
    runs-on: ubuntu-latest
    container:
      image: cmscloud/al9-cms:latest
      options: --user root
    steps:
      - name: Checking_out_code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checking_python_3.9
        run: |
          echo "python version="`python3 -V`
          ls -la
          pwd
          python3 -m py_compile src/cmsstyle/cmsstyle.py
          ls -lh src/cmsstyle/__pycache__/
      - name: Checking_Cpp_compilation
        run: |
          cd src
          echo '{gROOT->LoadMacro("cmsstyle.C++");}' > compiling.C

          dnf install -y root
          echo "ROOT version="`root-config --version`
          root -q compiling.C
          ls -lh cmsstyle_C.so
#
  py2-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (on host) for python 2.7 check
        uses: actions/checkout@v4

      - name: Run checks inside container for python 2.7 check
        uses: addnab/docker-run-action@v3
        with:
          image: cmscloud/cc7-cms:latest
          options: --user root -v ${{ github.workspace }}:/code -w /code
          run: |
            python -V
            find . -type f
            python -m py_compile src/cmsstyle/cmsstyle.py
            ls -lh src/cmsstyle/cmsstyle.pyc
#
